import Head from 'next/head'
import React from 'react'
import { Inter } from '@next/font/google'
import axios from 'axios'
// import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [inputValue, setInputValue] = React.useState("")
  const [hasil, setHasil] = React.useState(<></>)
  const handleSegitiga = React.useCallback(() => {
    axios.get(`/api/segitiga`, { params: { input: inputValue } })
    .then(res => {
      const response = res.data.result.map((item, id) => <div key={id}>
        { item }
      </div>)
      setHasil(response)
    })
  }, [inputValue])
  const handleGanjil = React.useCallback(() => {
    axios.get(`/api/ganjil`, { params: { input: inputValue } })
    .then(res => {
      const response = res.data.result.map((item, id) => <div key={id}>
        { item }
      </div>)
      setHasil(response)
    })
  }, [inputValue])
  const handlePrima = React.useCallback(() => {
    axios.get(`/api/prima`, { params: { input: inputValue } })
    .then(res => {
      const response = res.data.result.map((item, id) => <div key={id}>
        { item }
      </div>)
      setHasil(response)
    })
  }, [inputValue])  
  return (
    <>
      <Head>
        <title>Test_technical_code</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            .send {
              margin-right: 1rem;
              margin-top: 1rem;
            }
          `}
        </style>
      </Head>
      <main style={{ margin: "4rem" }}>
        <div>
          <input type="number" onChange={e => setInputValue(e.target.value)}/>
        </div>
        <div>
          <button className="send" onClick={handleSegitiga}>Generate Segitiga</button>
          <button className="send" onClick={handleGanjil}>Generate Bilangan Ganjil</button>
          <button className="send" onClick={handlePrima}>Generate Bilangan Prima</button>
        </div>
        <h2 style={{marginTop: "2rem"}}>
          Result:
        </h2>
        <div>
            { hasil }
        </div>
      </main>
    </>
  )
}
